Catch open_channel messages
salemove/ex_freddy pull request #36
Opened 2020-11-20 02:11 UTC by IceDragon200

While not the most elegant solution in the world, it has proven to work extremely well in production, so I'll open this PR.

Sorry about the extra commit that exposes `&get_last_error/1`, I needed that previously when debugging for a different reason.

## Synposis

Actors would leak channels when `open_channel` would timeout, the module's default implementation would ignore these messages or pass them up to the handler module (which would sometimes just ignore it as well), this has the nasty side effect of leaking channels when the channel was finally opened, but after the open_channel window was gone.

This PR adds a handler for those cases, if the actor already has an active channel and an old one arrives, it will immediately close it and continue using it's old one. 
If it didn't have a channel at the time, it would use the newly opened one and cancel its next connection step.

This was tested both in a production system and on local (by placing rabbitmq behind toxiproxy with a 1 second latency to simulate an extremely slow connection) 

In both tests it has caught all cases, connected successfully, operated normally and hasn't leaked a single channel since.

## Related

Closes #7

2020-11-20 07:10 UTC, take-five requested changes
Thank you for the PR! 👍 

Generally, looks good to me. However, is this really necessary to merge the first commit?

2020-11-20 07:10 UTC, take-five commented on lib/freddy/connection.ex
> +    Connection.call(connection, {:close, timeout}, timeout + 100)
Is this needed? Is so, could you please explain the reasoning behind it?

2020-11-20 07:10 UTC, take-five commented on lib/freddy/core/actor.ex
> +    Channel.close(channel)
Is this a synchronous operation? Could it potentially block the process?

2020-11-20 07:10 UTC, take-five commented on lib/freddy/core/actor.ex
> +  def connect(_info, state) do
Under which circumstances this clause is reachable?

2020-11-20 15:43 UTC, IceDragon200 commented on lib/freddy/core/actor.ex
> +  def connect(_info, state) do
In the case the channel open failed previously (most likely a timeout), and then it received the channel through the info message, the connection is still in the process of retrying due to the backoff, that case is there to catch it.

It triggers when the connection already has a channel from the aforementioned process, and is effectively a no-op.

Once that is over the channel enters its normal state and can be considered stable.

2020-11-20 15:43 UTC, IceDragon200 commented on lib/freddy/core/actor.ex
> +    Channel.close(channel)
It is synchronous from what I know, it will block, and it should block.

The actor still isn't in it's 'correct' state at this point, since it's resolving a channel conflict, once that's over it shouldn't be a problem, worst case it takes just a few more seconds to start in case of a conflict (you're on a latency ridden network already)

2020-11-20 15:43 UTC, IceDragon200 commented on lib/freddy/connection.ex
> +    Connection.call(connection, {:close, timeout}, timeout + 100)
The channel will attempt to close within the specified timeout, but the call can expire before the timeout actually triggers.

Say the channel's timing is off my a few milliseconds, the call would abort waiting for the response from process and return a timeout immediately to the caller, but then the close_channel finishes and returns an info message (the actual response)

You normally want the outer timeout to be longer than the internal to allow the process time to clean up after itself

2020-11-20 15:52 UTC, IceDragon200 commented
As for the first commit, I had problems originally where the connection was swallowing transport errors, we had the PROXY protocol enabled and I couldn't figure out why it wouldn't connect, because I couldn't see the connection errors at all.
As a last resort I added that function to figure it out and carry on with normal life. 

If it is problem, I'll remove it.

2020-12-17 08:47 UTC, take-five commented on lib/freddy/connection.ex
> +    Connection.call(connection, {:close, timeout}, timeout + 100)
This can fail if someone calls it with timeout `:infinity`, which is allowed value for timeouts.

2020-12-18 03:12 UTC, IceDragon200 commented on lib/freddy/connection.ex
> +    Connection.call(connection, {:close, timeout}, timeout + 100)
Yeah... you're right, that's something I completely overlooked, I've reverted the change

2020-12-18 03:14 UTC, take-five approved these changes

2020-12-18 03:25 UTC, merged

2020-12-18 08:29 UTC, take-five commented
Version 0.16.0 is released. Thanks again!